In [1]:
import numpy as np
print(np.__version__)

2.4.3


In [5]:
# Données linéaires (séries temporelles, caractéristiques d’un modèle ML)
vecteur = np.array([20,30,40,50])
print(vecteur)
print(f"Shape : {vecteur.shape} ")


[20 30 40 50]
Shape : (4,) 


In [7]:
#algèbre linéaire et Machine Learning
matrice_2d = np.array([[20,30,40,50],[20,30,40,50]])
print(matrice_2d)
print(f"Shape : {matrice_2d.shape} ")

[[20 30 40 50]
 [20 30 40 50]]
Shape : (2, 4) 


In [15]:
#vision par ordinateur et Deep Learning (ex: images avec RGB)
matrice_3d = np.array([[[20,30,40],[20,30,40]],[[20,30,40],[30,30,40]]])
print(matrice_3d)
print(f"Shape : {matrice_3d.shape} ")

[[[20 30 40]
  [20 30 40]]

 [[20 30 40]
  [30 30 40]]]
Shape : (2, 2, 3) 


In [36]:
#réseaux de neurones (Deep Learning), analyse volumétrique (IRM, 3D)...
matrice_4d = np.random.rand(2,3,4,5)
print(matrice_4d)
print(f"Shape : {matrice_4d.shape} ")
print(f"Size : {matrice_4d.size} ")

[[[[0.11588094 0.51119444 0.18471322 0.19008629 0.25399909]
   [0.84290083 0.69593274 0.36874307 0.44299173 0.51811722]
   [0.20753115 0.35781827 0.77900547 0.98117825 0.11547032]
   [0.03678095 0.41699918 0.74042674 0.42097799 0.00255208]]

  [[0.28769513 0.37138118 0.49720689 0.22961664 0.65444929]
   [0.47402684 0.90721269 0.4424049  0.7345976  0.90265487]
   [0.34308905 0.96596    0.52065748 0.1596914  0.06257326]
   [0.08502914 0.27555275 0.66220014 0.74227648 0.27536492]]

  [[0.70543631 0.22938384 0.35430517 0.08362968 0.6924314 ]
   [0.91818074 0.2874712  0.45815595 0.6684213  0.83583378]
   [0.34371601 0.87567526 0.69247846 0.50144288 0.83077302]
   [0.02531717 0.288682   0.80925909 0.65784566 0.29422456]]]


 [[[0.03544556 0.44420261 0.41061575 0.62377031 0.72743868]
   [0.0916145  0.89181095 0.04942744 0.00525325 0.83306961]
   [0.65199831 0.67650854 0.23305881 0.01706702 0.96918133]
   [0.40726294 0.41227054 0.14893335 0.05251716 0.79981413]]

  [[0.96318602 0.20359075 0.05

In [28]:
zeros_1d = np.zeros(5)
print(zeros_1d)

[0. 0. 0. 0. 0.]


In [29]:
zeros_2d = np.zeros((3,4))
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
ones_1d = np.ones(5)
print(ones_1d)

[1. 1. 1. 1. 1.]


In [32]:
ones_2d = np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
random_1d = np.random.rand(4)
print(random_1d)

[0.40695264 0.74440869 0.05035976 0.63986025]


In [35]:
random_2d = np.random.rand(3,4)
print(random_2d)

[[0.84776248 0.89554455 0.67200147 0.48704145]
 [0.21770908 0.10240592 0.65478074 0.47189923]
 [0.55654404 0.01751469 0.35179959 0.34224527]]


In [45]:
#reshape 
A = np.array([20,30,40,50])
B = A.reshape(4,1)
print(f"Shape : {A.shape} ")
print(f"Matrice after reshape : {B} ")

Shape : (4,) 
Matrice after reshape : [[20]
 [30]
 [40]
 [50]] 
